In [16]:
import numpy as np
import matplotlib.pyplot as plt

In [28]:
x = [1, 2, 3, 4, 5]
np_arr = np.array(x)
np_arr

array([1, 2, 3, 4, 5])

In [29]:
N=3

In [30]:
np.vander(x, N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [43]:
x = np.array([1, 2, 3,4,5])
np.vander(x)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [44]:
np.vander(x, increasing=True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])